name: "🐛 Bug Report"
description: Report something that's not working
title: "[BUG] "
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      placeholder: Describe the bug in detail.
    validations:
      required: true
  - type: input
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: "1. Go to...\n2. Click on...\n3. Error shows up"
