name: "✨ Feature Request"
description: Suggest a new feature
title: "[FEATURE] "
labels: [enhancement]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe your idea
      placeholder: What would you like to see added?
